[package]
name = "mayland"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["clock", "std"] }
libc = "0.2.157"
tracing = "0.1.40"
tracing-panic = "0.1.2"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
xcursor = "0.3.8"

[dependencies.smithay]
git = "https://github.com/Smithay/smithay"
version = "0.3.0"
default-features = false
features = [
	"backend_drm",
	"backend_egl",
	"backend_gbm",
	"backend_libinput",
	"backend_udev",
	"backend_session_libseat",
	"backend_winit",
	"desktop",
	"renderer_glow",
	"use_system_lib",
	"wayland_frontend",
]

[dependencies.smithay-drm-extras]
git = "https://github.com/Smithay/smithay"
default-features = false

[lints.clippy]
new_without_default = "allow"
undocumented_unsafe_blocks = "warn"

[features]
default = []
debug = []
trace = ["debug"]
