[package]
name = "mayland-comm"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
serde = { workspace = true, features = ["derive"] }

[lints]
workspace = true
